import Mathlib

namespace PCPPR.Location

/-- Deterministic payoff advantage of A when the rival chooses A with probability p. -/
def D (p dA dB : ℝ) : ℝ := p * dA + (1 - p) * dB

/-- Unclipped cutoff best response generated by a Uniform[-H,H] fit shock. -/
def BR (H dA dB p : ℝ) : ℝ := 1 / 2 + D p dA dB / (2 * H)

def u0 (H dB : ℝ) : ℝ := (H + dB) / (2 * H)

def u1 (H dA : ℝ) : ℝ := (H + dA) / (2 * H)

def B (H dA dB : ℝ) : ℝ := (dA - dB) / (2 * H)

/-- Paper equation (15): the cutoff rule is affine. -/
theorem BR_affine (H dA dB p : ℝ) (hH : H ≠ 0) :
    BR H dA dB p = u0 H dB + B H dA dB * p := by
  unfold BR D u0 B
  field_simp [hH]
  ring

/-- Endpoint definitions imply B=u1-u0. -/
theorem B_eq_u1_sub_u0 (H dA dB : ℝ) (hH : H ≠ 0) :
    B H dA dB = u1 H dA - u0 H dB := by
  unfold B u1 u0
  field_simp [hH]
  ring

/-- T6: 0<u0,u1<1 is enough to imply |B|<1, with no Banach theorem needed. -/
theorem endpoint_interior_implies_contraction
    {H dA dB : ℝ} (hH : H ≠ 0)
    (hu0 : 0 < u0 H dB ∧ u0 H dB < 1)
    (hu1 : 0 < u1 H dA ∧ u1 H dA < 1) :
    |B H dA dB| < 1 := by
  rw [B_eq_u1_sub_u0 H dA dB hH, abs_lt]
  constructor <;> linarith [hu0.1, hu0.2, hu1.1, hu1.2]

/-- Closed-form fixed point reported in paper equation (16). -/
def pStar (H dA dB : ℝ) : ℝ := (H + dB) / (2 * H - dA + dB)

/-- The reported pStar is a fixed point of the unclipped cutoff BR. -/
theorem pStar_is_fixed
    (H dA dB : ℝ)
    (hH : H ≠ 0)
    (hden : 2 * H - dA + dB ≠ 0) :
    BR H dA dB (pStar H dA dB) = pStar H dA dB := by
  unfold BR D pStar
  field_simp [hH, hden]
  ring

/-- An affine scalar best response with |B|<1 has at most one fixed point. -/
theorem affine_fixed_point_unique
    {u slope p p' : ℝ} (hs : |slope| < 1)
    (hp : p = u + slope * p)
    (hp' : p' = u + slope * p') : p = p' := by
  have hne : 1 - slope ≠ 0 := by
    have hlt := (abs_lt.mp hs).2
    linarith
  have hz : (1 - slope) * (p - p') = 0 := by
    nlinarith [hp, hp']
  have : p - p' = 0 := (mul_eq_zero.mp hz).resolve_left hne
  linarith

/-- T6: the simultaneous two-firm affine probability system cannot have an
asymmetric solution when |B|<1. -/
theorem no_asymmetric_probability_fixed_point
    {u slope p1 p2 : ℝ} (hs : |slope| < 1)
    (h1 : p1 = u + slope * p2)
    (h2 : p2 = u + slope * p1) : p1 = p2 := by
  have hpos : 0 < 1 + slope := by
    have hlo := (abs_lt.mp hs).1
    linarith
  have hz : (1 + slope) * (p1 - p2) = 0 := by
    nlinarith [h1, h2]
  have hne : 1 + slope ≠ 0 := ne_of_gt hpos
  have : p1 - p2 = 0 := (mul_eq_zero.mp hz).resolve_left hne
  linarith

/-- Combined uniqueness statement for the two-firm affine location system. -/
theorem affine_pair_unique
    {u slope p p1 p2 : ℝ} (hs : |slope| < 1)
    (hp : p = u + slope * p)
    (h1 : p1 = u + slope * p2)
    (h2 : p2 = u + slope * p1) : p1 = p ∧ p2 = p := by
  have heq : p1 = p2 := no_asymmetric_probability_fixed_point hs h1 h2
  subst p2
  have hp1 : p1 = u + slope * p1 := h1
  have huniq := affine_fixed_point_unique hs hp1 hp
  exact ⟨huniq, huniq⟩

end PCPPR.Location
